services:
  # Backend service
  - type: web
    name: rag-chatbot-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd Serverside && npm install
    startCommand: cd Serverside && node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://rag-chatbot-frontend.onrender.com
      - key: BACKEND_URL
        value: https://rag-chatbot-backend.onrender.com
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true

  # Frontend service
  - type: web
    name: rag-chatbot-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd chatbot-genesis-react && npm install && npm run build
    staticPublishPath: ./chatbot-genesis-react/dist
    envVars:
      - key: VITE_API_URL
        value: https://rag-chatbot-backend.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true 